name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install xz-utils
        sudo mkdir -p ./xdev
        sudo wget https://github.com/roemvaar/baremetal-qemu-aarch64/releases/download/1.0/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf.tar.xz
        sudo tar -xaf arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf.tar.xz -C ./xdev/

    - name: Build
      run:  |
        make X_DIR=./xdev/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf
    
    - name: Test
      run: |
        git submodule update --init --recursive
        cd test
        make test
