name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --exclude=test/Unity --filter=-legal/copyright,-whitespace/braces,-readability/casting,-build/include_subdir,-build/header_guard,-runtime/int --linelength=120 --quiet --recursive .

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install xz-utils
        sudo mkdir -p ./xdev
        sudo wget https://github.com/roemvaar/baremetal-qemu-aarch64/releases/download/1.0/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf.tar.xz
        sudo tar -xaf arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf.tar.xz -C ./xdev/

    - name: Build
      run:  |
        make X_DIR=./xdev/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf
    
    - name: Test
      run: |
        git submodule update --init --recursive
        cd test
        make test

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Tests
      run: |
        git submodule update --init --recursive
        cd test
        make test

    - name: Run Tests
      run: ./test
