name: CI

on:
  push:
  workflow_dispatch:
    inputs:
      clear-cache:
      description: Clear cache
      required: false
      default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install 