name: CI

on:
  push:
  workflow_dispatch:
    inputs:
      clear-cache:
      description: Clear cache
      required: false
      default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          wget https://github.com/roemvaar/baremetal-qemu-aarch64/blob/main/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf.tar.xz
